# Script thiết lập Server Test cho Web và Mobile
# EcoCheck OLP 2025

Write-Host "========================================" -ForegroundColor Cyan
Write-Host "  EcoCheck - Test Server Setup" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""

# 1. Lấy Local IP
Write-Host "[1/5] Lấy Local IP Address..." -ForegroundColor Yellow
$localIP = (Get-NetIPAddress -AddressFamily IPv4 | Where-Object { 
    $_.IPAddress -notlike "127.*" -and 
    $_.IPAddress -notlike "169.254.*" -and
    $_.InterfaceAlias -notlike "*Loopback*"
} | Select-Object -First 1).IPAddress

if (-not $localIP) {
    $localIP = "localhost"
    Write-Host "⚠️  Không tìm thấy Local IP, sử dụng: $localIP" -ForegroundColor Yellow
} else {
    Write-Host "✅ Local IP: $localIP" -ForegroundColor Green
}
Write-Host ""

# 2. Kiểm tra Docker
Write-Host "[2/5] Kiểm tra Docker..." -ForegroundColor Yellow
try {
    docker ps | Out-Null
    Write-Host "✅ Docker đang chạy" -ForegroundColor Green
} catch {
    Write-Host "❌ Docker chưa chạy! Vui lòng khởi động Docker Desktop" -ForegroundColor Red
    exit 1
}
Write-Host ""

# 3. Khởi động Services
Write-Host "[3/5] Khởi động Docker Services..." -ForegroundColor Yellow
docker compose up -d
Start-Sleep -Seconds 5
Write-Host "✅ Services đã khởi động" -ForegroundColor Green
Write-Host ""

# 4. Kiểm tra Backend
Write-Host "[4/5] Kiểm tra Backend API..." -ForegroundColor Yellow
$maxRetries = 10
$retryCount = 0
$backendReady = $false

while ($retryCount -lt $maxRetries -and -not $backendReady) {
    try {
        $response = Invoke-WebRequest -Uri "http://localhost:3000/health" -TimeoutSec 2 -UseBasicParsing
        if ($response.StatusCode -eq 200) {
            $backendReady = $true
            Write-Host "✅ Backend API đang chạy" -ForegroundColor Green
        }
    } catch {
        $retryCount++
        Write-Host "   Đang đợi backend... ($retryCount/$maxRetries)" -ForegroundColor Gray
        Start-Sleep -Seconds 2
    }
}

if (-not $backendReady) {
    Write-Host "⚠️  Backend chưa sẵn sàng sau $maxRetries lần thử" -ForegroundColor Yellow
}
Write-Host ""

# 5. Hiển thị thông tin kết nối
Write-Host "[5/5] Thông tin kết nối:" -ForegroundColor Yellow
Write-Host ""
Write-Host "========================================" -ForegroundColor Cyan
Write-Host "  🌐 WEB PLATFORM" -ForegroundColor Green
Write-Host "========================================" -ForegroundColor Cyan
Write-Host "  Frontend Web:  http://localhost:3001" -ForegroundColor Yellow
Write-Host "  Backend API:   http://localhost:3000" -ForegroundColor Yellow
Write-Host ""

Write-Host "========================================" -ForegroundColor Cyan
Write-Host "  📱 MOBILE PLATFORM" -ForegroundColor Green
Write-Host "========================================" -ForegroundColor Cyan
Write-Host "  Android Emulator:" -ForegroundColor Yellow
Write-Host "    Base URL: http://10.0.2.2:3000" -ForegroundColor White
Write-Host ""
Write-Host "  iOS Simulator:" -ForegroundColor Yellow
Write-Host "    Base URL: http://localhost:3000" -ForegroundColor White
Write-Host ""
Write-Host "  Real Device (WiFi):" -ForegroundColor Yellow
Write-Host "    Base URL: http://$localIP:3000" -ForegroundColor White
Write-Host "    (Đảm bảo device và máy tính cùng mạng WiFi)" -ForegroundColor Gray
Write-Host ""

Write-Host "========================================" -ForegroundColor Cyan
Write-Host "  🔧 TEST ENDPOINTS" -ForegroundColor Green
Write-Host "========================================" -ForegroundColor Cyan
Write-Host "  Health Check:  http://localhost:3000/health" -ForegroundColor Yellow
Write-Host "  API Status:    http://localhost:3000/api/status" -ForegroundColor Yellow
Write-Host ""

Write-Host "========================================" -ForegroundColor Cyan
Write-Host "  📋 NEXT STEPS" -ForegroundColor Green
Write-Host "========================================" -ForegroundColor Cyan
Write-Host "  1. Web: Mở trình duyệt → http://localhost:3001" -ForegroundColor White
Write-Host "  2. Mobile:" -ForegroundColor White
Write-Host "     - Android: Cập nhật baseUrl trong api_constants.dart" -ForegroundColor Gray
Write-Host "     - iOS: Sử dụng localhost:3000" -ForegroundColor Gray
Write-Host "     - Real Device: Sử dụng http://$localIP:3000" -ForegroundColor Gray
Write-Host "  3. Test kết nối: Chạy ./test-connection.ps1" -ForegroundColor White
Write-Host ""

# Tạo file config cho mobile
$mobileConfig = @"
# Mobile API Configuration
# Generated by setup-test-server.ps1

# Android Emulator
ANDROID_BASE_URL=http://10.0.2.2:3000

# iOS Simulator  
IOS_BASE_URL=http://localhost:3000

# Real Device (Update with your local IP)
REAL_DEVICE_BASE_URL=http://$localIP:3000
"@

$configPath = "mobile-api-config.txt"
$mobileConfig | Out-File -FilePath $configPath -Encoding utf8
Write-Host "✅ Đã tạo file $configPath" -ForegroundColor Green
Write-Host ""

